apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: achordia/nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
  # imagePullSecrets:
  #   - name: regcred
