apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      # envFrom:
      #   - configMapRef:
      #       name: app-configmap
      # env:
      #   - name: APP_COLOR
      #     valueFrom:
      #       configMapKeyRef:
      #         name: color
      #         key: app-configmap
      volumeMounts:
        - name: app-configmap-vol
          mountPath: /tmp

  volumes:
    - name: app-configmap-vol
      configMap:
        name: app-configmap