apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      # envFrom:
      #   - secretRef:
      #       name: app-secret
      # env:
      #   - name: APP_COLOR
      #     valueFrom:
      #       secretKeyRef:
      #         name: color
      #         key: app-secret
      volumeMounts:
        - name: app-secret-vol
          mountPath: /tmp

  volumes:
    - name: app-secret-vol
      secret:
        secretName: app-secret