apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080