apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080